parameters:
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: null
  database_name: main
  database_user: main
  database_password: 123456

  mailer_transport: smtp
  mailer_host: mail.easytoinvest.net
  mailer_user: support@easytoinvest.net
  mailer_password: q1w2e3r4t5
  locale: ru
  secret: 760c640b956ea8106efaa5d1adc7c46fc1ba9563
  database_path: ~