security:
    encoders:
        Main\MainBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        user_db:
            entity: { class: Main\MainBundle\Entity\User, property: username }

    role_hierarchy:
            ADMIN_ROLE:       USER_ROLE
            SUPER_ADMIN_ROLE: [ADMIN_ROLE, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            anonymous: ~

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check

            logout:
                path: /logout
                target: main_login


    access_control:
    #    - { path: ^/user, roles: USER_ROLE }
    #    - { path: ^/user/statistics, roles: USER_ROLE }
    #    - { path: ^/admin, roles: [USER_ROLE, ADMIN_ROLE] }
    #    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
