security:
    encoders:
        Main\MainBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        user_db:
            entity: { class: Main\MainBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            anonymous: ~

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check

            logout:
                path: /logout
                target: /home


    access_control:
        - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: USER_ROLE }
        - { path: ^/user/activateAcount, roles: USER_ROLE }
        - { path: ^/user/statistics, roles: USER_ROLE }
        - { path: ^/admin/*, roles: ADMIN_ROLE }