security:
    encoders:
        Main\MainBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        user_db:
            entity: { class: Main\MainBundle\Entity\User, property: username }

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            anonymous: ~

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check

            logout:
                path: /logout
                target: main_login


    access_control:
        - { path: ^/user, roles: [ROLE_USER] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
