main:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: main_login
        permanent: true

main_signup:
    pattern: /signup
    defaults: { _controller: MainMainBundle:Index:registerCheckId }

main_signup_action:
    pattern: /signup_action
    defaults: { _controller: MainMainBundle:Index:register }

main_login:
    path: /login
    defaults: { _controller: MainMainBundle:Index:login }

main_login_check:
    path: /login_check
    defaults: { _controller: MainMainBundle:Index:loginCheck }

main_logout:
    path: /logout

main_userpage:
    path: /user
    defaults: { _controller: MainMainBundle:User:account }

main_userpage_active_account:
    path: /user/active_account
    defaults: { _controller: MainMainBundle:User:active_account }

main_userpage_statistics:
    path: /user/statistics
    defaults: { _controller: MainMainBundle:User:statistics }

main_userpage_my_team:
    path: /user/my_team
    defaults: { _controller: MainMainBundle:User:myTeam }

main_userpage_account:
    path: /user/account
    defaults: { _controller: MainMainBundle:User:account }

main_userpage_change_profile:
    path: /user/change_profile
    defaults: { _controller: MainMainBundle:User:changeProfile }

main_activate_acount:
    path: /user/activateAcount
    defaults: { _controller: MainMainBundle:User:activateAcount }

main_withdraw_money:
    path: /user/withdrawMoney
    defaults: { _controller: MainMainBundle:User:withdrawMoney }

main_balance:
    path: /user/balance
    defaults: { _controller: MainMainBundle:User:balance }
