main:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: main_homepage
        permanent: true

main_homepage:
    path: /home
    defaults: { _controller: MainMainBundle:Index:index }

main_signup:
    pattern: /signup/{sponsor_id}
    defaults: { _controller: MainMainBundle:Index:registerCheckId }

main_signup_action:
    pattern: /signup_action/{sponsor_id}
    defaults: { _controller: MainMainBundle:Index:register }

main_login:
    path: /login
    defaults: { _controller: MainMainBundle:Index:login }

main_login_check:
    path: /login_check
    defaults: { _controller: MainMainBundle:Index:loginCheck }

main_logout:
    path: /logout

main_userpage:
    path: /user
    defaults: { _controller: MainMainBundle:User:index }

main_userpage_statistics:
    path: /user/statistics
    defaults: { _controller: MainMainBundle:User:statistics }

main_activate_acount:
    path: /user/activateAcount
    defaults: { _controller: MainMainBundle:User:activateAcount }