main:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: main_login
        permanent: true

main_signup:
    pattern: /signup
    defaults: { _controller: MainMainBundle:Index:registerCheckId }

main_signup_action:
    pattern: /signup_action
    defaults: { _controller: MainMainBundle:Index:register }

main_login:
    path: /login
    defaults: { _controller: MainMainBundle:Index:login }

main_login_forgot_password:
    pattern: /login/forgot_password
    defaults: { _controller: MainMainBundle:Index:forgotPassword }

main_reset_password_page:
    pattern: /reset_password/{keyForAccess}
    defaults: { _controller: MainMainBundle:Index:resetPassword }

main_reset_password_save:
    pattern: /reset_password_save/{userid}
    defaults: { _controller: MainMainBundle:Index:resetPasswordSave }

main_login_check:
    path: /login_check
    defaults: { _controller: MainMainBundle:Index:loginCheck }

main_logout:
    path: /logout

main_userpage:
    path: /user
    defaults: { _controller: MainMainBundle:User:account }

main_userpage_statistics:
    path: /user/statistics
    defaults: { _controller: MainMainBundle:User:statistics }

main_userpage_my_team:
    path: /user/my_team
    defaults: { _controller: MainMainBundle:User:myTeam }

main_userpage_account:
    path: /user/account
    defaults: { _controller: MainMainBundle:User:account }

main_userpage_change_profile:
    path: /user/change_profile
    defaults: { _controller: MainMainBundle:User:changeProfile }

main_userpage_change_password:
    path: /user/change_password
    defaults: { _controller: MainMainBundle:User:changePassword }

main_userpage_change_perfect_money:
    pattern: /user/change_perfect_money
    defaults: { _controller: MainMainBundle:User:changePerfectMoney }

main_userpage_change_perfect_money_page:
    pattern: /user/change_perfect_money/{keyForAccess}
    defaults: { _controller: MainMainBundle:User:changePerfectMoneyChange }

main_userpage_change_perfect_money_page_save:
    path: /user/change_perfect_money_save
    defaults: { _controller: MainMainBundle:User:changePerfectMoneySave }

main_activate_acount:
    path: /user/activateAcount
    defaults: { _controller: MainMainBundle:User:activateAcount }

main_withdraw_money:
    path: /user/withdrawMoney
    defaults: { _controller: MainMainBundle:User:withdrawMoney }

main_balance:
    path: /user/balance
    defaults: { _controller: MainMainBundle:User:balance }

main_admin_panel:
    path: /admin
    defaults: { _controller: MainMainBundle:Admin:index }

main_invest_money:
    path: /user/investMoney
    defaults: { _controller: MainMainBundle:User:investMoney }

main_admin_change_perfect_money:
    path: /admin/change_perfect_money
    defaults: { _controller: MainMainBundle:Admin:changePerfectMoneySettings }
